# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: VeracodePipelineScan@0
  displayName: VeracodePipelineScan
  inputs:
    fileToScan: '$(System.DefaultWorkingDirectory)/target/verademo.war'
    breakPipeline: false
    baselineFileGeneration: false

- task: Veracode@3
  displayName: 'Upload and scan: $(System.DefaultWorkingDirectory)'
  inputs:
    ConnectionDetailsSelection: Credentials
    apiId: '$(vid)'
    apiKey: '$(vkey)'
    veracodeAppProfile: 'AzureDevOps-VeraDemo'
    filepath: '$(System.DefaultWorkingDirectory)/target/verademo.war'
    importResults: true    